

services:
  #PHP Service
  app:
    image: 6fb2166a8af52b49bef6210ee40aa8fd62db6eb2d7d7a6e3988e6a2c3e6c92f8
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      COMPOSER_MEMORY_LIMIT: -1
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '8058:80'
    volumes:
      - ./:/var/www/
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default

#Docker Networks
networks:
  default:
