

services:
  #PHP Service
  app:
    image: 684b13c0a4197ccb9ef65f0cb0c1df0373a74610ee494f9316a6f685bf80e12b
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      COMPOSER_MEMORY_LIMIT: -1
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '8058:80'
    volumes:
      - ./:/var/www/
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default

#Docker Networks
networks:
  default:
